kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: wasmtime
nodes:
  - role: control-plane
    image: kind-crun-wasmtime
    labels:
      runtime/wasmtime: "true"
      kubernetes.azure.com/wasmtime-spin-v1: "true"
      kubernetes.azure.com/wasmtime-slight-v1: "true"
