---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-spin
spec:
  selector:
    matchLabels:
      app: wasm-spin
  template:
    metadata:
      labels:
        app: wasm-spin
    spec:
      runtimeClassName: wasmtime-spin-v1
      containers:
        - name: testwasm
          image: spin-app:v0.1.0
          command: ["/"]
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: wasm-spin
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wasm-spin
